version: '3.9'
services:
  database:
    image: postgres:15
    container_name: bytebank_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: terrorbite
      POSTGRES_DB: bytebank_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend/bank-management-application
      dockerfile: Dockerfile
    container_name: bank-management-application
    ports:
      - "8080:8080"
    environment: spring.datasource.url=${SPRING_DATASOURCE_URL} spring.datasource.username=${SPRING_DATASOURCE_USERNAME} spring.datasource.password=${SPRING_DATASOURCE_PASSWORD} spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO} spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
    depends_on:
      - database

volumes:
  postgres_data:
